using UnityEngine;

namespace Chipstix.ExampleBall
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Effects/Material Changer")]
#endif
    public class MaterialChanger : Effects.MaterialChanger
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
