using UnityEngine;

namespace Chipstix.ExampleBall
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Animation Components/Export Animation Component")]
#endif
    public class ExportAnimationComponent : global::ExportAnimationComponent
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
