using UnityEngine;

namespace Chipstix.ExampleBall
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Animation Components/Pipe Valve Animation Component")]
#endif
    public class PipeValveAnimationComponent : global::PipeValveAnimComponent
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
